on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
          - name: Configure SSH
            run: |
              mkdir -p ~/.ssh/
              echo "$SSH_KEY" > ~/.ssh/staging.key
              chmod 600 ~/.ssh/staging.key
              cat >>~/.ssh/config <<END
              Host staging
                HostName $SSH_HOST
                Port $SSH_PORT
                User $SSH_USERNAME
                IdentityFile ~/.ssh/staging.key
                StrictHostKeyChecking no
              END
            env:
              SSH_USERNAME: ${{ secrets.USERNAME }}
              SSH_KEY: ${{ secrets.KEY }}
              SSH_PORT: ${{ secrets.PORT }}
              SSH_HOST: ${{ secrets.HOST }}

          - name: Remove deploy the server
            run: ssh staging "cd bitscalc && git pull && make deploy"
